/*
 * This source file was generated by the Gradle 'init' task
 */
package gerenciador_doacoes;

import java.io.IOException;

import gerenciador_doacoes.ui.PaginaPrincipal;

public class App {
 

    public static void main(String[] args) throws IOException {

        
        PaginaPrincipal paginaInicial = new PaginaPrincipal();
        paginaInicial.MostrarMenu();
    }
}
